server:
  port: 8386
  servlet:
    context-path: /management

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test3"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    enabled: false

